[package]
name = "cad_data_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
notify = "7"
notify-debouncer-mini = "0.5"
crossbeam-channel = "0.5"
rfd = "0.15"

[lib]
name = "cad_data_loader"
path = "src/lib.rs"
