[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
interface_codegen_macro = { path = "../../../interface/codegen/server" }
sim_manager = { path = "../sim_manager" }
qrcode = "0.14"
local-ip-address = "0.6"

[lib]
name = "server"
path = "src/lib.rs"
